"""App-Store API client. # --- BEGIN generated by sdk/codegen/facade — do not edit ---"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from scrapebadger._internal.client import BaseClient


class AppStoreClient:
    """Client for all App-Store API operations. (Generated from the OpenAPI spec.)"""

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    async def get_app_detail(
        self,
        app_id: str,
        *,
        country: str = "us",
        lang: str | None = None,
        include_extras: bool = True,
    ) -> dict[str, Any]:
        """Get app detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {"country": country, "lang": lang, "include_extras": include_extras}.items()
            if v is not None
        }
        return await self._client.get(f"/v1/app-store/apps/{app_id}", params=params)

    async def get_app_reviews(
        self, app_id: str, *, country: str = "us", page: int = 1, sort: str = "mostRecent"
    ) -> dict[str, Any]:
        """Get app reviews.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {"country": country, "page": page, "sort": sort}.items()
            if v is not None
        }
        return await self._client.get(f"/v1/app-store/apps/{app_id}/reviews", params=params)

    async def top_charts(
        self,
        *,
        country: str = "us",
        type: str = "top-free",
        genre: str | None = None,
        limit: int = 50,
        entity: str = "apps",
    ) -> dict[str, Any]:
        """Top charts.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "country": country,
                "type": type,
                "genre": genre,
                "limit": limit,
                "entity": entity,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/app-store/charts", params=params)

    async def get_developer_apps(self, artist_id: str, *, country: str = "us") -> dict[str, Any]:
        """Get developer apps.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"country": country}.items() if v is not None}
        return await self._client.get(f"/v1/app-store/developers/{artist_id}", params=params)

    async def list_genres(self) -> dict[str, Any]:
        """List genres.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get("/v1/app-store/genres")

    async def list_markets(self) -> dict[str, Any]:
        """List markets.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get("/v1/app-store/markets")

    async def search_apps(
        self,
        *,
        query: str,
        country: str = "us",
        entity: str = "software",
        limit: int = 25,
        offset: int = 0,
        lang: str | None = None,
    ) -> dict[str, Any]:
        """Search apps.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "query": query,
                "country": country,
                "entity": entity,
                "limit": limit,
                "offset": offset,
                "lang": lang,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/app-store/search", params=params)
