"""Google-Play API client. # --- BEGIN generated by sdk/codegen/facade — do not edit ---"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from scrapebadger._internal.client import BaseClient


class GooglePlayClient:
    """Client for all Google-Play API operations. (Generated from the OpenAPI spec.)"""

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    async def get_app_detail(
        self, app_id: str, *, country: str = "US", lang: str = "en"
    ) -> dict[str, Any]:
        """Get app detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"country": country, "lang": lang}.items() if v is not None}
        return await self._client.get(f"/v1/google-play/apps/{app_id}", params=params)

    async def get_app_permissions(self, app_id: str, *, lang: str = "en") -> dict[str, Any]:
        """Get app permissions.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"lang": lang}.items() if v is not None}
        return await self._client.get(f"/v1/google-play/apps/{app_id}/permissions", params=params)

    async def get_app_reviews(
        self,
        app_id: str,
        *,
        country: str = "US",
        lang: str = "en",
        sort: str = "newest",
        count: int = 40,
        page_token: str | None = None,
    ) -> dict[str, Any]:
        """Get app reviews.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "country": country,
                "lang": lang,
                "sort": sort,
                "count": count,
                "page_token": page_token,
            }.items()
            if v is not None
        }
        return await self._client.get(f"/v1/google-play/apps/{app_id}/reviews", params=params)

    async def get_similar_apps(
        self, app_id: str, *, country: str = "US", lang: str = "en"
    ) -> dict[str, Any]:
        """Get similar apps.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"country": country, "lang": lang}.items() if v is not None}
        return await self._client.get(f"/v1/google-play/apps/{app_id}/similar", params=params)

    async def list_categories(self) -> dict[str, Any]:
        """List categories.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get("/v1/google-play/categories")

    async def browse_a_category(
        self, category_id: str, *, country: str = "US", lang: str = "en", num: int = 100
    ) -> dict[str, Any]:
        """Browse a category.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v for k, v in {"country": country, "lang": lang, "num": num}.items() if v is not None
        }
        return await self._client.get(f"/v1/google-play/categories/{category_id}", params=params)

    async def top_charts(
        self,
        collection: str,
        *,
        category: str = "APPLICATION",
        country: str = "US",
        lang: str = "en",
    ) -> dict[str, Any]:
        """Top charts.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {"category": category, "country": country, "lang": lang}.items()
            if v is not None
        }
        return await self._client.get(f"/v1/google-play/collections/{collection}", params=params)

    async def get_developer_apps(
        self, developer: str, *, country: str = "US", lang: str = "en", num: int = 100
    ) -> dict[str, Any]:
        """Get developer apps.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v for k, v in {"country": country, "lang": lang, "num": num}.items() if v is not None
        }
        return await self._client.get(f"/v1/google-play/developers/{developer}", params=params)

    async def list_markets(self) -> dict[str, Any]:
        """List markets.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get("/v1/google-play/markets")

    async def search_apps(
        self, *, query: str, country: str = "US", lang: str = "en", price: str | None = None
    ) -> dict[str, Any]:
        """Search apps.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {"query": query, "country": country, "lang": lang, "price": price}.items()
            if v is not None
        }
        return await self._client.get("/v1/google-play/search", params=params)
