"""Airbnb API client. # --- BEGIN generated by sdk/codegen/facade — do not edit ---"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from scrapebadger._internal.client import BaseClient


class AirbnbClient:
    """Client for all Airbnb API operations. (Generated from the OpenAPI spec.)"""

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    async def search_experiences(
        self,
        *,
        location: str,
        cursor: str | None = None,
        currency: str | None = None,
        locale: str | None = None,
    ) -> dict[str, Any]:
        """Search experiences.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "location": location,
                "cursor": cursor,
                "currency": currency,
                "locale": locale,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/airbnb/experiences", params=params)

    async def get_experience_detail(
        self,
        experience_id: str,
        *,
        adults: int = 1,
        children: int = 0,
        infants: int = 0,
        currency: str | None = None,
        locale: str | None = None,
    ) -> dict[str, Any]:
        """Get experience detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "adults": adults,
                "children": children,
                "infants": infants,
                "currency": currency,
                "locale": locale,
            }.items()
            if v is not None
        }
        return await self._client.get(f"/v1/airbnb/experiences/{experience_id}", params=params)

    async def get_listing_detail(
        self,
        room_id: str,
        *,
        adults: int = 1,
        currency: str | None = None,
        locale: str | None = None,
    ) -> dict[str, Any]:
        """Get listing detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {"adults": adults, "currency": currency, "locale": locale}.items()
            if v is not None
        }
        return await self._client.get(f"/v1/airbnb/listings/{room_id}", params=params)

    async def get_availability_calendar(
        self,
        room_id: str,
        *,
        month: int = 1,
        year: int = 2026,
        months: int = 12,
        currency: str | None = None,
        locale: str | None = None,
    ) -> dict[str, Any]:
        """Get availability calendar.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "month": month,
                "year": year,
                "months": months,
                "currency": currency,
                "locale": locale,
            }.items()
            if v is not None
        }
        return await self._client.get(f"/v1/airbnb/listings/{room_id}/calendar", params=params)

    async def get_listing_reviews(
        self,
        room_id: str,
        *,
        limit: int = 24,
        offset: int = 0,
        sort: str = "MOST_RECENT",
        currency: str | None = None,
        locale: str | None = None,
    ) -> dict[str, Any]:
        """Get listing reviews.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "offset": offset,
                "sort": sort,
                "currency": currency,
                "locale": locale,
            }.items()
            if v is not None
        }
        return await self._client.get(f"/v1/airbnb/listings/{room_id}/reviews", params=params)

    async def search_stays(
        self,
        *,
        location: str | None = None,
        ne_lat: str | None = None,
        ne_lng: str | None = None,
        sw_lat: str | None = None,
        sw_lng: str | None = None,
        check_in: str | None = None,
        check_out: str | None = None,
        adults: int = 1,
        children: int = 0,
        infants: int = 0,
        pets: int = 0,
        price_min: str | None = None,
        price_max: str | None = None,
        min_bedrooms: str | None = None,
        min_beds: str | None = None,
        min_bathrooms: str | None = None,
        room_type: str | None = None,
        cursor: str | None = None,
        limit: int = 18,
        currency: str | None = None,
        locale: str | None = None,
    ) -> dict[str, Any]:
        """Search stays.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "location": location,
                "ne_lat": ne_lat,
                "ne_lng": ne_lng,
                "sw_lat": sw_lat,
                "sw_lng": sw_lng,
                "check_in": check_in,
                "check_out": check_out,
                "adults": adults,
                "children": children,
                "infants": infants,
                "pets": pets,
                "price_min": price_min,
                "price_max": price_max,
                "min_bedrooms": min_bedrooms,
                "min_beds": min_beds,
                "min_bathrooms": min_bathrooms,
                "room_type": room_type,
                "cursor": cursor,
                "limit": limit,
                "currency": currency,
                "locale": locale,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/airbnb/search", params=params)
