"""Account API client. # --- BEGIN generated by sdk/codegen/facade — do not edit ---"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from scrapebadger._internal.client import BaseClient


class AccountClient:
    """Client for all Account API operations. (Generated from the OpenAPI spec.)"""

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    async def get_account_info(self) -> dict[str, Any]:
        """Get account info.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get("/v1/account/me")
