"""Booking API client. # --- BEGIN generated by sdk/codegen/facade — do not edit ---"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from scrapebadger._internal.client import BaseClient


class BookingClient:
    """Client for all Booking API operations. (Generated from the OpenAPI spec.)"""

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    async def search_destinations(
        self, *, query: str, limit: int = 8, language: str | None = None
    ) -> dict[str, Any]:
        """Search destinations.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {"query": query, "limit": limit, "language": language}.items()
            if v is not None
        }
        return await self._client.get("/v1/booking/destinations", params=params)

    async def get_property_detail(
        self,
        country_code: str,
        slug: str,
        *,
        photos: int = 40,
        questions: int = 10,
        language: str | None = None,
    ) -> dict[str, Any]:
        """Get property detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {"photos": photos, "questions": questions, "language": language}.items()
            if v is not None
        }
        return await self._client.get(
            f"/v1/booking/properties/{country_code}/{slug}", params=params
        )

    async def get_property_reviews(
        self,
        country_code: str,
        slug: str,
        *,
        limit: int = 25,
        offset: int = 0,
        sort: str = "MOST_RELEVANT",
        review_language: str | None = None,
        guest_type: str | None = None,
        language: str | None = None,
    ) -> dict[str, Any]:
        """Get property reviews.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "offset": offset,
                "sort": sort,
                "review_language": review_language,
                "guest_type": guest_type,
                "language": language,
            }.items()
            if v is not None
        }
        return await self._client.get(
            f"/v1/booking/properties/{country_code}/{slug}/reviews", params=params
        )

    async def get_room_types_and_live_rates(
        self,
        country_code: str,
        slug: str,
        *,
        checkin: str,
        checkout: str,
        adults: int = 2,
        children: str | None = None,
        rooms: int = 1,
        currency: str | None = None,
        language: str | None = None,
    ) -> dict[str, Any]:
        """Get room types and live rates.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "checkin": checkin,
                "checkout": checkout,
                "adults": adults,
                "children": children,
                "rooms": rooms,
                "currency": currency,
                "language": language,
            }.items()
            if v is not None
        }
        return await self._client.get(
            f"/v1/booking/properties/{country_code}/{slug}/rooms", params=params
        )

    async def search_properties(
        self,
        *,
        location: str | None = None,
        dest_id: str | None = None,
        dest_type: str = "NO_DEST_TYPE",
        checkin: str | None = None,
        checkout: str | None = None,
        adults: int = 2,
        children: str | None = None,
        rooms: int = 1,
        offset: int = 0,
        limit: int = 25,
        sort: str | None = None,
        filters: str | None = None,
        currency: str | None = None,
        language: str | None = None,
    ) -> dict[str, Any]:
        """Search properties.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "location": location,
                "dest_id": dest_id,
                "dest_type": dest_type,
                "checkin": checkin,
                "checkout": checkout,
                "adults": adults,
                "children": children,
                "rooms": rooms,
                "offset": offset,
                "limit": limit,
                "sort": sort,
                "filters": filters,
                "currency": currency,
                "language": language,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/booking/search", params=params)
