"""Perplexity API client. # --- generated by sdk/codegen/facade — do not edit ---"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from scrapebadger._internal.client import BaseClient


class PerplexityClient:
    """Client for all Perplexity API operations. (Generated from the OpenAPI spec.)"""

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    async def ask_perplexity_a_question(
        self, *, prompt: str, country: str | None = None
    ) -> dict[str, Any]:
        """Ask Perplexity a question.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"prompt": prompt, "country": country}.items() if v is not None}
        return await self._client.get("/v1/perplexity/ask", params=params)

    async def ask_perplexity_a_question_post(
        self, *, payload: dict[str, Any] | None = None, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """Ask Perplexity a question (POST).

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.post("/v1/perplexity/ask", params=params, json=payload)

    async def measure_a_brand_s_visibility_in_a_perplexity_answer(
        self,
        *,
        prompt: str,
        brand: str,
        domain: str | None = None,
        aliases: str | None = None,
        competitors: str | None = None,
        country: str | None = None,
    ) -> dict[str, Any]:
        """Measure a brand's visibility in a Perplexity answer.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "prompt": prompt,
                "brand": brand,
                "domain": domain,
                "aliases": aliases,
                "competitors": competitors,
                "country": country,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/perplexity/brand-visibility", params=params)

    async def measure_a_brand_s_visibility_in_a_perplexity_answer_post(
        self, *, payload: dict[str, Any] | None = None, params: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """Measure a brand's visibility in a Perplexity answer (POST).

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.post(
            "/v1/perplexity/brand-visibility", params=params, json=payload
        )
