"""Idealista API client. # --- generated by sdk/codegen/facade — do not edit ---"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from scrapebadger._internal.client import BaseClient


class IdealistaClient:
    """Client for all Idealista API operations. (Generated from the OpenAPI spec.)"""

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    async def agency_by_phone(
        self,
        phone: str,
        *,
        market: str = "es",
        operation: str | None = None,
        property_type: str | None = None,
        page: int = 1,
        max_items: int = 30,
        include_listings: bool = True,
    ) -> dict[str, Any]:
        """Agency by phone.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "market": market,
                "operation": operation,
                "property_type": property_type,
                "page": page,
                "max_items": max_items,
                "include_listings": include_listings,
            }.items()
            if v is not None
        }
        return await self._client.get(f"/v1/idealista/agency/by-phone/{phone}", params=params)

    async def agency_profile_listings(
        self,
        short_name: str,
        *,
        market: str = "es",
        operation: str | None = None,
        property_type: str | None = None,
        page: int = 1,
        max_items: int = 30,
        include_listings: bool = True,
    ) -> dict[str, Any]:
        """Agency profile + listings.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "market": market,
                "operation": operation,
                "property_type": property_type,
                "page": page,
                "max_items": max_items,
                "include_listings": include_listings,
            }.items()
            if v is not None
        }
        return await self._client.get(f"/v1/idealista/agency/{short_name}", params=params)

    async def list_markets(self) -> dict[str, Any]:
        """List markets.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get("/v1/idealista/markets")

    async def get_property_detail(
        self, property_code: str, *, market: str = "es", locale: str = "en"
    ) -> dict[str, Any]:
        """Get property detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"market": market, "locale": locale}.items() if v is not None}
        return await self._client.get(f"/v1/idealista/properties/{property_code}", params=params)

    async def get_listing_engagement_stats(
        self, property_code: str, *, market: str = "es", locale: str = "en"
    ) -> dict[str, Any]:
        """Get listing engagement stats.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"market": market, "locale": locale}.items() if v is not None}
        return await self._client.get(
            f"/v1/idealista/properties/{property_code}/stats", params=params
        )

    async def search_listings(
        self,
        *,
        location: str,
        operation: str = "sale",
        property_type: str = "homes",
        market: str = "es",
        page: int = 1,
        max_items: int = 30,
        sort_by: str | None = None,
        sort_order: str = "desc",
        min_price: str | None = None,
        max_price: str | None = None,
        min_size: str | None = None,
        max_size: str | None = None,
        min_rooms: str | None = None,
        max_rooms: str | None = None,
        locale: str | None = None,
    ) -> dict[str, Any]:
        """Search listings.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "location": location,
                "operation": operation,
                "property_type": property_type,
                "market": market,
                "page": page,
                "max_items": max_items,
                "sort_by": sort_by,
                "sort_order": sort_order,
                "min_price": min_price,
                "max_price": max_price,
                "min_size": min_size,
                "max_size": max_size,
                "min_rooms": min_rooms,
                "max_rooms": max_rooms,
                "locale": locale,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/idealista/search", params=params)

    async def search_all_beats_result_cap(
        self,
        *,
        location: str,
        operation: str = "sale",
        property_type: str = "homes",
        market: str = "es",
        max_results: int = 500,
        min_price: str | None = None,
        max_price: str | None = None,
        min_size: str | None = None,
        max_size: str | None = None,
        min_rooms: str | None = None,
        max_rooms: str | None = None,
        locale: str | None = None,
    ) -> dict[str, Any]:
        """Search all (beats result cap).

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "location": location,
                "operation": operation,
                "property_type": property_type,
                "market": market,
                "max_results": max_results,
                "min_price": min_price,
                "max_price": max_price,
                "min_size": min_size,
                "max_size": max_size,
                "min_rooms": min_rooms,
                "max_rooms": max_rooms,
                "locale": locale,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/idealista/search/all", params=params)

    async def resolve_locations(
        self,
        *,
        query: str,
        operation: str = "sale",
        property_type: str = "homes",
        market: str = "es",
        locale: str | None = None,
    ) -> dict[str, Any]:
        """Resolve locations.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "query": query,
                "operation": operation,
                "property_type": property_type,
                "market": market,
                "locale": locale,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/idealista/suggest", params=params)
