"""Facebook API client. # --- BEGIN generated by sdk/codegen/facade — do not edit ---"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from scrapebadger._internal.client import BaseClient


class FacebookClient:
    """Client for all Facebook API operations. (Generated from the OpenAPI spec.)"""

    def __init__(self, client: BaseClient) -> None:
        self._client = client

    async def search_advertiser_pages(self, *, query: str, country: str = "US") -> dict[str, Any]:
        """Search advertiser pages.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"query": query, "country": country}.items() if v is not None}
        return await self._client.get("/v1/facebook/ads/pages/search", params=params)

    async def get_advertiser_page_info(
        self, page_id: str, *, country: str = "US"
    ) -> dict[str, Any]:
        """Get advertiser page info.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"country": country}.items() if v is not None}
        return await self._client.get(f"/v1/facebook/ads/pages/{page_id}", params=params)

    async def search_the_ad_library(
        self,
        *,
        query: str,
        country: str = "US",
        ad_type: str = "all",
        active_status: str = "active",
        after: str | None = None,
    ) -> dict[str, Any]:
        """Search the Ad Library.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "query": query,
                "country": country,
                "ad_type": ad_type,
                "active_status": active_status,
                "after": after,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/facebook/ads/search", params=params)

    async def get_an_ad(self, ad_archive_id: str, *, country: str = "US") -> dict[str, Any]:
        """Get an ad.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"country": country}.items() if v is not None}
        return await self._client.get(f"/v1/facebook/ads/{ad_archive_id}", params=params)

    async def get_group_detail(self, group_id: str) -> dict[str, Any]:
        """Get group detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get(f"/v1/facebook/groups/{group_id}")

    async def get_group_posts(self, group_id: str, *, after: str | None = None) -> dict[str, Any]:
        """Get group posts.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"after": after}.items() if v is not None}
        return await self._client.get(f"/v1/facebook/groups/{group_id}/posts", params=params)

    async def list_categories(self) -> dict[str, Any]:
        """List categories.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get("/v1/facebook/marketplace/categories")

    async def browse_a_marketplace_category(
        self,
        category: str,
        *,
        location: str = "nyc",
        min_price: str | None = None,
        max_price: str | None = None,
        sort_by: str | None = None,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Browse a Marketplace category.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "location": location,
                "min_price": min_price,
                "max_price": max_price,
                "sort_by": sort_by,
                "after": after,
            }.items()
            if v is not None
        }
        return await self._client.get(
            f"/v1/facebook/marketplace/category/{category}", params=params
        )

    async def get_a_marketplace_item(self, item_id: str) -> dict[str, Any]:
        """Get a Marketplace item.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get(f"/v1/facebook/marketplace/item/{item_id}")

    async def list_locations(self) -> dict[str, Any]:
        """List locations.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get("/v1/facebook/marketplace/locations")

    async def search_marketplace(
        self,
        *,
        query: str,
        location: str = "nyc",
        min_price: str | None = None,
        max_price: str | None = None,
        days_since_listed: str | None = None,
        sort_by: str | None = None,
        item_condition: str | None = None,
        delivery_method: str | None = None,
        after: str | None = None,
    ) -> dict[str, Any]:
        """Search Marketplace.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {
            k: v
            for k, v in {
                "query": query,
                "location": location,
                "min_price": min_price,
                "max_price": max_price,
                "days_since_listed": days_since_listed,
                "sort_by": sort_by,
                "item_condition": item_condition,
                "delivery_method": delivery_method,
                "after": after,
            }.items()
            if v is not None
        }
        return await self._client.get("/v1/facebook/marketplace/search", params=params)

    async def get_page_detail(self, identifier: str) -> dict[str, Any]:
        """Get page detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get(f"/v1/facebook/pages/{identifier}")

    async def get_page_posts(self, identifier: str, *, after: str | None = None) -> dict[str, Any]:
        """Get page posts.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"after": after}.items() if v is not None}
        return await self._client.get(f"/v1/facebook/pages/{identifier}/posts", params=params)

    async def get_post_detail(self, post_id: str) -> dict[str, Any]:
        """Get post detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get(f"/v1/facebook/posts/{post_id}")

    async def get_post_comments(
        self, post_id: str, *, after: str | None = None, sort: str = "relevance"
    ) -> dict[str, Any]:
        """Get post comments.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"after": after, "sort": sort}.items() if v is not None}
        return await self._client.get(f"/v1/facebook/posts/{post_id}/comments", params=params)

    async def get_profile_detail(self, identifier: str) -> dict[str, Any]:
        """Get profile detail.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        return await self._client.get(f"/v1/facebook/profiles/{identifier}")

    async def get_profile_posts(
        self, identifier: str, *, after: str | None = None
    ) -> dict[str, Any]:
        """Get profile posts.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"after": after}.items() if v is not None}
        return await self._client.get(f"/v1/facebook/profiles/{identifier}/posts", params=params)

    async def search_everything(self, *, q: str, after: str | None = None) -> dict[str, Any]:
        """Search everything.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"q": q, "after": after}.items() if v is not None}
        return await self._client.get("/v1/facebook/search", params=params)

    async def search_events(self, *, q: str, after: str | None = None) -> dict[str, Any]:
        """Search events.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"q": q, "after": after}.items() if v is not None}
        return await self._client.get("/v1/facebook/search/events", params=params)

    async def search_groups(self, *, q: str, after: str | None = None) -> dict[str, Any]:
        """Search groups.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"q": q, "after": after}.items() if v is not None}
        return await self._client.get("/v1/facebook/search/groups", params=params)

    async def search_pages(self, *, q: str, after: str | None = None) -> dict[str, Any]:
        """Search Pages.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"q": q, "after": after}.items() if v is not None}
        return await self._client.get("/v1/facebook/search/pages", params=params)

    async def search_people(self, *, q: str, after: str | None = None) -> dict[str, Any]:
        """Search people.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"q": q, "after": after}.items() if v is not None}
        return await self._client.get("/v1/facebook/search/people", params=params)

    async def search_places(self, *, q: str, after: str | None = None) -> dict[str, Any]:
        """Search places.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"q": q, "after": after}.items() if v is not None}
        return await self._client.get("/v1/facebook/search/places", params=params)

    async def search_posts(self, *, q: str, after: str | None = None) -> dict[str, Any]:
        """Search posts.

        Generated from the OpenAPI spec; returns the raw response dict.
        """
        params = {k: v for k, v in {"q": q, "after": after}.items() if v is not None}
        return await self._client.get("/v1/facebook/search/posts", params=params)
