"""Naver API module for ScrapeBadger SDK.

This module provides a comprehensive async client for scraping Naver data
through the ScrapeBadger API. All methods are async and return strongly-typed
Pydantic models.

Naver is the dominant Korean portal and commerce platform. The client exposes
integrated and vertical search, Place detail/reviews/photos, Shopping rankings
and finder/catalog search, SmartStore / Brand stores, commerce products with
reviews and Q&A, and Shopping Live.

Example:
    ```python
    from scrapebadger import ScrapeBadger

    async with ScrapeBadger(api_key="your-key") as client:
        results = await client.naver.search.search("\ucee4\ud53c\uba38\uc2e0")
        top = await client.naver.shopping.bestsellers()
        store = await client.naver.stores.get("somestore")
    ```
"""

from scrapebadger.naver.client import NaverClient
from scrapebadger.naver.models import (
    AutocompleteResponse,
    AutocompleteSuggestion,
    BlogResponse,
    BlogResult,
    CafeResponse,
    CafeResult,
    ClipResponse,
    ClipResult,
    FilterValue,
    GroupProductGraphResponse,
    GroupReviewSummaryResponse,
    ImageResponse,
    ImageResult,
    InsightKeyword,
    KeywordPeriod,
    KinResponse,
    KinResult,
    LiveBroadcastCategoriesResponse,
    LiveBroadcastCountsResponse,
    LiveBroadcastDetailResponse,
    LiveBroadcastProductsResponse,
    LiveChannelBroadcastsResponse,
    LiveChannelProductsResponse,
    LiveChannelProfileResponse,
    LiveChannelShortclipsResponse,
    LiveProductCategory,
    LiveReplayProductsResponse,
    LiveSearchKeywordsResponse,
    LiveShortclipDetailResponse,
    LiveShortclipProductsResponse,
    LocalSearchResponse,
    MenuEntry,
    NewsResponse,
    NewsResult,
    PaginatedReviewsResponse,
    PlaceDetailResponse,
    PlacePhoto,
    PlacePhotosResponse,
    PlaceReview,
    PlaceReviewsResponse,
    PlaceSummary,
    PriceCompareEntry,
    PriceCompareOffer,
    PriceCompareResponse,
    ProductDetailResponse,
    ProductQna,
    ProductQnaResponse,
    ProductReviewSummaryResponse,
    RelatedSearch,
    ReviewDetailResponse,
    ReviewSsrQueriesResponse,
    ReviewVideoInkeyResponse,
    SearchResponse,
    SearchResult,
    ShoppingBestsellerProduct,
    ShoppingBestsellersResponse,
    ShoppingBrandCategoriesResponse,
    ShoppingBrandRankEntry,
    ShoppingBrandRankResponse,
    ShoppingCatalogSearchResponse,
    ShoppingCategoriesResponse,
    ShoppingCategory,
    ShoppingCategoryTreeResponse,
    ShoppingDealsResponse,
    ShoppingFilter,
    ShoppingFilteredProductsResponse,
    ShoppingInsightResponse,
    ShoppingItItemsResponse,
    ShoppingKeyword,
    ShoppingKeywordPeriodsResponse,
    ShoppingKeywordRankResponse,
    ShoppingSearchFiltersResponse,
    ShoppingSearchProductsResponse,
    ShoppingVerticalResponse,
    StoreBestsellersResponse,
    StoreCategoriesResponse,
    StoreCategory,
    StoreProductsResponse,
    StoreProfileResponse,
    VideoResponse,
    VideoResult,
    WebResult,
    WebSearchResponse,
)

__all__ = [
    # Models
    "AutocompleteResponse",
    "AutocompleteSuggestion",
    "BlogResponse",
    "BlogResult",
    "CafeResponse",
    "CafeResult",
    "ClipResponse",
    "ClipResult",
    "FilterValue",
    "GroupProductGraphResponse",
    "GroupReviewSummaryResponse",
    "ImageResponse",
    "ImageResult",
    "InsightKeyword",
    "KeywordPeriod",
    "KinResponse",
    "KinResult",
    "LiveBroadcastCategoriesResponse",
    "LiveBroadcastCountsResponse",
    "LiveBroadcastDetailResponse",
    "LiveBroadcastProductsResponse",
    "LiveChannelBroadcastsResponse",
    "LiveChannelProductsResponse",
    "LiveChannelProfileResponse",
    "LiveChannelShortclipsResponse",
    "LiveProductCategory",
    "LiveReplayProductsResponse",
    "LiveSearchKeywordsResponse",
    "LiveShortclipDetailResponse",
    "LiveShortclipProductsResponse",
    "LocalSearchResponse",
    "MenuEntry",
    # Client
    "NaverClient",
    "NewsResponse",
    "NewsResult",
    "PaginatedReviewsResponse",
    "PlaceDetailResponse",
    "PlacePhoto",
    "PlacePhotosResponse",
    "PlaceReview",
    "PlaceReviewsResponse",
    "PlaceSummary",
    "PriceCompareEntry",
    "PriceCompareOffer",
    "PriceCompareResponse",
    "ProductDetailResponse",
    "ProductQna",
    "ProductQnaResponse",
    "ProductReviewSummaryResponse",
    "RelatedSearch",
    "ReviewDetailResponse",
    "ReviewSsrQueriesResponse",
    "ReviewVideoInkeyResponse",
    "SearchResponse",
    "SearchResult",
    "ShoppingBestsellerProduct",
    "ShoppingBestsellersResponse",
    "ShoppingBrandCategoriesResponse",
    "ShoppingBrandRankEntry",
    "ShoppingBrandRankResponse",
    "ShoppingCatalogSearchResponse",
    "ShoppingCategoriesResponse",
    "ShoppingCategory",
    "ShoppingCategoryTreeResponse",
    "ShoppingDealsResponse",
    "ShoppingFilter",
    "ShoppingFilteredProductsResponse",
    "ShoppingInsightResponse",
    "ShoppingItItemsResponse",
    "ShoppingKeyword",
    "ShoppingKeywordPeriodsResponse",
    "ShoppingKeywordRankResponse",
    "ShoppingSearchFiltersResponse",
    "ShoppingSearchProductsResponse",
    "ShoppingVerticalResponse",
    "StoreBestsellersResponse",
    "StoreCategoriesResponse",
    "StoreCategory",
    "StoreProductsResponse",
    "StoreProfileResponse",
    "VideoResponse",
    "VideoResult",
    "WebResult",
    "WebSearchResponse",
]
